<a href="https://colab.research.google.com/github/yogiraj542/cie/blob/main/cie_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
data=fetch_california_housing()
data


{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [ ]:
df=pd.DataFrame(data.data,columns=data.feature_names)
df['PRICE']=data.target
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  PRICE  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [ ]:
df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude         PRICE  
count  20640.000000  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704      2.068558  
std       10.386050      2.135952      2.003532      1.153956  
min        0.692308     32.540000   -124.350000      0.149990  
25%        2.429741     33.930000   -121.800000      1.196000  
50%        2.818116     34.260000   -118.490000      1.797000  
75%        3.282261     37.710000   -118.010000      2.647250  
max     1243.333333     41.950000   -114.310000      5.000010

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   PRICE       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


In [ ]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
PRICE         0
dtype: int64

In [ ]:
X=df.drop('PRICE',axis=1)
Y=df['PRICE']=data.target
X
Y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=5,test_size=0.5)
X_train

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
19363  2.7171      38.0  8.295455   1.767045       569.0  3.232955     38.70   
10894  3.4130      37.0  3.581454   1.072682      2089.0  5.235589     33.72   
12818  3.4291       6.0  4.804158   1.065646      1982.0  2.168490     38.61   
4377   4.1667      48.0  5.339161   1.031469       589.0  2.059441     34.09   
1570   7.7072      34.0  7.144487   1.007605       729.0  2.771863     37.84   
...       ...       ...       ...        ...         ...       ...       ...   
5520   6.5778      46.0  6.561194   1.050746       839.0  2.504478     33.97   
3046   2.4044      34.0  5.478632   1.079772      1101.0  3.136752     35.50   
20463  5.8096      20.0  8.165888   1.049065      1629.0  3.806075     34.27   
18638  3.5943      14.0  5.001474   1.071481      3416.0  2.517318     36.99   
2915   4.3482       9.0  5.792453   1.103774       409.0  1.929245     35.36   

       Longitude  
19363    -123.24  
10894    -117.86  
12818    -121.49  
4377     -118.27  
1570     -122.02  
...          ...  
5520     -118.39  
3046     -119.28  
20463    -118.75  
18638    -121.98  
2915     -119.06  

[10320 rows x 8 columns]

In [ ]:
Y_train

array([1.313, 1.506, 1.053, ..., 2.644, 2.624, 0.952])

In [19]:
md.(LinearRegression)

SyntaxError: invalid syntax (<ipython-input-19-9d9d8c23b435>, line 1)

In [21]:
Y_pred=Model.predict(X_test)
Y_pred


array([1.71744356, 1.9472404 , 0.93867412, ..., 1.73874658, 1.63034064,
       1.4999002 ])

In [22]:
r_score=rscore.data